### ISSUE TITLE
Basic parser for Vita

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/mafiaconfiscatedassets#14]
The dataset is available at the following url

https://goo.gl/4zVr8a

The basic parse takes into account just the followinf field: latitude, longitute, Descrizione (parsed as rdfs:label), Assegnato (define two class for Assigned or not), Eventuali altre criticità (ad rdfs:description), Gestore (usare Organization Ontology), indirizzo

**Comment by Giorgiooliva** [comment]
Penso che era comprensivo in quello che  ho fatto!
