### ISSUE TITLE
[calatafimi] errori di validazione

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/mafiaconfiscatedassets#21]
Il validatore https://www.w3.org/RDF/Validator/ restituisce i seguenti errori per il file assetsAll.owl di calatafimi-segesta

> Error: {E201} rdf:about not allowed as attribute here.[Line = 43, Column = 66]
> Error: {E202} Expecting XML start or end element(s). String data "37.824261" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 44, Column = 20]
> Error: {E201} Multiple children of property element[Line = 45, Column = 12]
> Error: {E202} Expecting XML start or end element(s). String data "12.87573" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 45, Column = 20]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 47, Column = 36]
> Error: {E202} Expecting XML start or end element(s). String data "Appezzamento di Terreno con insistente fabbricato costituito da un capannone (piano terra e scantinato) adiacante a due fabbricati a doppia elevazione, ad uffici e servizi igienici e un piccolo fabbricato ad una elevaizone adibito ad alloggio caldaia e gruppo elettrogeno. completano l'impianto un edificio per alloggio custode e una cabina per l'alloggio di apparecchiature per l'impianto di depurazione. Il Comune di Calatafimi-Segesta con delibera della Giunta Municipale n. 221 del 22/12/2014 ha preso atto del provvedimento di concessione n. 40 del 17/12/2014 emesso dal Presidente del GAL Elimos con cui � stato concesso un contributo imponibile di euro 398.420,14 corrispondente al 100% della spesa ritenuta amminssibile oltre a euro 63.441,58 per iva a rimborso per la "realizzaizone di piattaforma logistica a servizio delle imprese agricolo, per lavori di manutenzione straordinaria " not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 48, Column = 908]
> Error: {E201} Multiple children of property element[Line = 49, Column = 76]
> Error: {E201} rdf:resource not allowed as attribute here.[Line = 49, Column = 76]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 51, Column = 70]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 53, Column = 79]
> Error: {E202} Expecting XML start or end element(s). String data "Contrada Coriolano, Calatafimi-Segesta, IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 54, Column = 59]
> Error: {E201} Multiple children of property element[Line = 55, Column = 22]
> Error: {E202} Expecting XML start or end element(s). String data "Contrada Coriolano, Calatafimi-Segesta, IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 55, Column = 65]
> Error: {E201} Multiple children of property element[Line = 56, Column = 19]
> Error: {E202} Expecting XML start or end element(s). String data "Calatafimi-Segesta" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 56, Column = 37]
> Error: {E201} Multiple children of property element[Line = 57, Column = 22]
> Error: {E202} Expecting XML start or end element(s). String data "IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 57, Column = 24]
> Error: {E201} Multiple children of property element[Line = 60, Column = 66]
> Error: {E201} Multiple children of property element[Line = 64, Column = 36]
> Error: {E201} Multiple children of property element[Line = 68, Column = 67]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 77, Column = 63]
> Error: {E202} Expecting XML start or end element(s). String data "37,943512" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 78, Column = 20]
> Error: {E201} Multiple children of property element[Line = 79, Column = 12]
> Error: {E202} Expecting XML start or end element(s). String data "12,834838" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 79, Column = 21]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 81, Column = 36]
> Error: {E202} Expecting XML start or end element(s). String data "Fondo rustico" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 82, Column = 27]
> Error: {E201} Multiple children of property element[Line = 83, Column = 76]
> Error: {E201} rdf:resource not allowed as attribute here.[Line = 83, Column = 76]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 85, Column = 70]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 87, Column = 79]
> Error: {E202} Expecting XML start or end element(s). String data "Contrada Angimb�, Calatafimi-Segesta, IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 88, Column = 57]
> Error: {E201} Multiple children of property element[Line = 89, Column = 22]
> Error: {E202} Expecting XML start or end element(s). String data "Contrada Angimb�, Calatafimi-Segesta, IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 89, Column = 63]
> Error: {E201} Multiple children of property element[Line = 90, Column = 19]
> Error: {E202} Expecting XML start or end element(s). String data "Calatafimi-Segesta" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 90, Column = 37]
> Error: {E201} Multiple children of property element[Line = 91, Column = 22]
> Error: {E202} Expecting XML start or end element(s). String data "IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 91, Column = 24]
> Error: {E201} Multiple children of property element[Line = 94, Column = 66]
> Error: {E201} Multiple children of property element[Line = 98, Column = 36]
> Error: {E201} Multiple children of property element[Line = 102, Column = 71]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 111, Column = 67]
> Error: {E202} Expecting XML start or end element(s). String data "37,893588" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 112, Column = 20]
> Error: {E201} Multiple children of property element[Line = 113, Column = 12]
> Error: {E202} Expecting XML start or end element(s). String data "12,90467" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 113, Column = 20]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 115, Column = 36]
> Error: {E202} Expecting XML start or end element(s). String data "Terreno agricolo" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 116, Column = 30]
> Error: {E201} Multiple children of property element[Line = 117, Column = 72]
> Error: {E201} rdf:resource not allowed as attribute here.[Line = 117, Column = 72]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 119, Column = 66]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 121, Column = 75]
> Error: {E202} Expecting XML start or end element(s). String data "Contrada Nanfo, Calatafimi-Segesta, IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 122, Column = 55]
> Error: {E201} Multiple children of property element[Line = 123, Column = 22]
> Error: {E202} Expecting XML start or end element(s). String data "Contrada Nanfo, Calatafimi-Segesta, IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 123, Column = 61]
> Error: {E201} Multiple children of property element[Line = 124, Column = 19]
> Error: {E202} Expecting XML start or end element(s). String data "Calatafimi-Segesta" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 124, Column = 37]
> Error: {E201} Multiple children of property element[Line = 125, Column = 22]
> Error: {E202} Expecting XML start or end element(s). String data "IT" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 125, Column = 24]
> Error: {E201} Multiple children of property element[Line = 128, Column = 62]
> Error: {E201} Multiple children of property element[Line = 132, Column = 36]
> Error: {E201} Multiple children of property element[Line = 136, Column = 67]
> Error: {E201} rdf:about not allowed as attribute here.[Line = 145, Column = 63]
> Error: {E202} Expecting XML start or end element(s). String data "37,895277" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 146, Column = 20]
> Error: {E201} Multiple children of property element[Line = 147, Column = 12]
> Error: {E202} Expecting XML start or end element(s). String data "12,900363" not allowed. Maybe there should be an rdf:parseType='Literal' for embedding mixed XML content in RDF. Maybe a striping error.[Line = 147, Column = 21]

**Comment by cristianolongo** [comment]
se è possibile generare svariati ticket a partire da questo

**Comment by Giorgiooliva** [comment]
Risolto
