### ISSUE TITLE
[Calatafimi] Inserire collegamento alla geometry nelle locations

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/mafiaconfiscatedassets#22]
Sia nel file locations.owl che in assetsAll.owl ad ogni individuo di classe locn:Location deve essere associato il corrispondente individuo di classe geo:Point attraverso la proprietà locn:geometry. Vedi ad esempio http://www.opendatahacklab.org/mafiaconfiscatedassets/catania/locations.owl

**Comment by Giorgiooliva** [comment]
Cristiano io in questo file geo:Point non ne vedo !

**Comment by cristianolongo** [comment]
E' nel file geomerty o in assetsAll

**Comment by Giorgiooliva** [comment]
ah. in geometry  vabbe stasera faccio le modifiche, che ora sono a lavoro!
