### ISSUE TITLE
Remove old map for confiscated assets in Palermo

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/mafiaconfiscatedassets#9]
http://www.dmi.unict.it/~longo/locn/BeniConfiscatiPalermo.html

**Comment by cirospat** [comment]
non la rimuovere la mappa che hai fatto.
E' su Petrusino!
:-)

**Comment by cristianolongo** [comment]
Ok ma devo mettere il link alla nuova versione almeno.

**Comment by cirospat** [comment]
allora please fammelo sapere (il nuovo link) che devo aggiornare Petrusino 
:-)

**Comment by cirospat** [comment]
@cristianolongo mi puoi fare sapere il nuovo link delle mappe dei beni confiscati di Palermo e di Catania che aggiorno Petrusino? Grazie
